version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: mymysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: liujun
      MYSQL_DATABASE: could_disk
      LANG: C.UTF-8
    volumes:
      - ./db_data:/var/lib/mysql
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - "0.0.0.0:3308:3306"
    restart: unless-stopped
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
