// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type Response struct {
	Info string `json:"info"`
	Code int    `json:"code"`
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}
