// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type Response struct {
	Info string `json:"info"`
	Code int    `json:"code"`
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type UserLoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Info         string `json:"info"`
	Code         int    `json:"code"`
}
